### ISSUE TITLE
有关egovehicle的问题

### ISSUE THREAD

**Issue by zhouwy-lv** [chengxuxin/Lane_change_RL#1]
尊敬的作者，你好！
我是智能驾驶强化学习决策领域的研一学生，有幸拜读到您的文章。我想问一个问题，就是您把lane1全部定义为egovehicle，那么在一轮训练过程中是这条车道上所有的ego的数据都会被保存起来拿去训练是吗？也就是比如在lane1上的第二个ego，那它的前一个ego就变成了current lane leader C0 ，同样的，它后面的ego就变成了 Current lane follower C2,是这样理解的吗？也就是说当前这一轮有多少个ego就有多少组数据是吗？
谢谢！

**Comment by chengxuxin** [comment]
Hi！ 每一个episode 会随机选择lane1上的一辆车作为ego vehicle，不是全部的车。

**Comment by zhouwy-lv** [comment]
好的，谢谢！
